### ISSUE TITLE
module: 'nvim-treesitter.configs' not found

### ISSUE THREAD

**Issue by fivepixels** [windwp/nvim-ts-autotag#172]
Every time I install this plugin and run Neovim, I get this error. The thing is that I just installed it but did not configure anything. Even when I did use the setup function, I still got the exactly same error. Does anybody have any ideas for solving this problem?

<img width="1352" alt="Screenshot 2024-05-17 at 11 44 33 PM" src="https://github.com/windwp/nvim-ts-autotag/assets/96553411/cab1b5ac-276b-46dc-9c9a-78e24e71bca3">

--- all text
```
Error detected while processing /Users/cattynip/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:74: /Users/cattynip/.config/nvim/init
.lua../Users/cattynip/.local/share/nvim/site/pack/pckr/opt/nvim-ts-autotag/plugin/nvim-ts-autotag.vim, line 1: Vim(lua):E5108: Error ex
ecuting lua ...ckr/opt/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:2: module 'nvim-treesitter.configs' not found:
        no field package.preload['nvim-treesitter.configs']
        no file './nvim-treesitter/configs.lua'
        no file '/opt/homebrew/share/luajit-2.1/nvim-treesitter/configs.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/configs.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/configs/init.lua'
        no file '/opt/homebrew/share/lua/5.1/nvim-treesitter/configs.lua'
        no file '/opt/homebrew/share/lua/5.1/nvim-treesitter/configs/init.lua'
        no file './nvim-treesitter/configs.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter/configs.so'
        no file '/opt/homebrew/lib/lua/5.1/nvim-treesitter/configs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
        no file '/opt/homebrew/lib/lua/5.1/nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...ckr/opt/nvim-ts-autotag/lua/nvim-ts-autotag/internal.lua:2: in function 'chunk'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:49: in function <...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/l
oader.lua:47>
        [C]: in function 'require'
        ...te/pack/pckr/opt/nvim-ts-autotag/lua/nvim-ts-autotag.lua:1: in function 'chunk'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:49: in function <...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/l
oader.lua:47>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
        [C]: in function 'source'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:74: in function 'source_runtime'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:133: in function 'packadd'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:179: in function 'load_plugin'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:217: in function 'load_plugins'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:231: in function 'setup'
        ...s/cattynip/.local/share/nvim/pckr/pckr.nvim/lua/pckr.lua:60: in function 'add'
        /Users/cattynip/.config/nvim/lua/fivepixels/plugins.lua:3: in main chunk
        [C]: in function 'require'
        /Users/cattynip/.config/nvim/init.lua:3: in main chunk
stack traceback:
        [C]: in function 'source'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:74: in function 'source_runtime'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:133: in function 'packadd'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:179: in function 'load_plugin'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:217: in function 'load_plugins'
        ...nip/.local/share/nvim/pckr/pckr.nvim/lua/pckr/loader.lua:231: in function 'setup'
        ...s/cattynip/.local/share/nvim/pckr/pckr.nvim/lua/pckr.lua:60: in function 'add'
        /Users/cattynip/.config/nvim/lua/fivepixels/plugins.lua:3: in main chunk
        [C]: in function 'require'
        /Users/cattynip/.config/nvim/init.lua:3: in main chunk
```

**Comment by PriceHiller** [comment]
Hi @fivepixels, I've begun maintaining a fork over @ https://github.com/PriceHiller/nvim-ts-autotag/ that should be compatible with the latest breaking changes upstream until windwp hopefully comes back.

You may want to give it a shot until windwp is back 🙂.

**Comment by fivepixels** [comment]
Okay. I can just wait!

**Comment by PriceHiller** [comment]
Will be closed by #173

**Comment by PriceHiller** [comment]
Already resolved in #171 I believe

**Comment by fivepixels** [comment]
I still have the issue...

When I first installed this plugin again after removing it, I got this error,

<img width="1352" alt="Screenshot 2024-05-19 at 12 17 53 PM" src="https://github.com/windwp/nvim-ts-autotag/assets/96553411/2f3422ff-de24-4f86-8dad-5eb67bcde4d9">


After that, the long error below constantly showed up. The weird thing for both the past and now is that this error happens very sometimes when I open up the directory that does not use tsx or jsx, and it always shows this error when opening the directory that does have tsx or jsx files. 


<img width="1319" alt="Screenshot 2024-05-19 at 12 18 11 PM" src="https://github.com/windwp/nvim-ts-autotag/assets/96553411/f3979d16-bb47-4e6f-be3c-8987b07e7abf">
<img width="1352" alt="Screenshot 2024-05-19 at 12 18 04 PM" src="https://github.com/windwp/nvim-ts-autotag/assets/96553411/e5e50ab2-9ceb-421a-aa31-33008f1e8667">



I can see the source code for this plugin `~/.local/share/nvim/site/pack/pckr/opt/nvim-ts-autotag`, and its commits are 

<img width="1352" alt="Screenshot 2024-05-19 at 12 31 12 PM" src="https://github.com/windwp/nvim-ts-autotag/assets/96553411/4224a867-898b-499e-9c6b-0f706413a534">

**Comment by PriceHiller** [comment]
Should *now* be resolved with the merging of #173.

I'll be closing this issue as a result. If this is still a problem ping me and I'll investigate and reopen this issue.

Thanks 🙂
